name: Deploy uzERP Docs Site

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:

    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_KEY }}
        name: id_rsa
        known_hosts: ${{ secrets.KNOWN_HOSTS }}

    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Install nodejs
    - uses: actions/setup-node@v3
      with:
        node-version: 8.5.0

    - name: Install node packages
      run: npm install

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.93.3'
        extended: true

    - name: Build
      run: hugo

    - name: Deploy
      run: rsync --delete -rvzh ./public/ git@104.248.170.137:/var/www/html/doc.uzerp.com/
